### ISSUE TITLE
milestone 0.2.0

### ISSUE THREAD

**Issue by soasme** [soasme/bamboo#1]
- [ ] cli tool
  - [ ]  autoenv
  - [ ] autofind yaml
- [ ] production tool
  - [ ] db: github oauth login
  - [ ] db: env manipulate
  - [ ] db: prog manipulate(sync from github repo)
  - [ ] devops: auto build an artifact
  - [ ] devops: auto deploy to production
  - [ ] feature: better error log
  - [ ] feature: run history log
